Website/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Website.Models
{
    public class Location
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên địa điểm.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tọa độ.")]
        [RegularExpression("^[0-9]*\\.?[0-9]*$", ErrorMessage = "Vui lòng nhập số.")]
        public string Latitude { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tọa độ.")]
        [RegularExpression("^[0-9]*\\.?[0-9]*$", ErrorMessage = "Vui lòng nhập số.")]
        public string Longitude { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn thứ tự.")]
        public int Position { get; set; }
    }
}

Website/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class LocationController : Controller
    {
        // GET: Location
        public ActionResult Create()
        {
            if (Session["UserID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Location objLocation)
        {
            if (ModelState.IsValid)
            {
                using (DBModel db = new DBModel())
                {
                    var obj = db.location.Where(a => a.Name.Equals(objLocation.Name)).FirstOrDefault();
                    if (obj != null)
                    {
                        ViewBag.Message = "Địa điếm đã tồn tại.";
                        return View();
                    }
                    var objPos = db.location.Where(a => a.Position.Equals(objLocation.Position)).FirstOrDefault();
                    if (objPos != null)
                    {
                        ViewBag.Message = "Thứ tự đã được dùng cho địa điểm khác.";
                        return View();
                    }
                    else
                    {
                        try
                        {
                            var createObj = new Location();
                            createObj.Latitude = objLocation.Latitude;
                            createObj.Longitude = objLocation.Longitude;
                            createObj.Name = objLocation.Name;
                            createObj.Position = objLocation.Position;
                            createObj.Description = objLocation.Description;
                            db.location.Add(createObj);
                            db.SaveChanges();
                            ViewBag.Message = "Thêm địa điểm thành công.";
                            ModelState.Clear();
                            return View(new Location());
                        }
                        catch (Exception exception)
                        {
                            ViewBag.Message = exception;
                            return View();
                        }
                    }
                }
            }
            return View();
        }
    }
}

Website/Views/Location/Create.cshtml
@using Website.Models
@model Location
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Styles
{
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
}

@{
    var positionList = new SelectList(
        new List<SelectListItem>
        {
            new SelectListItem {Text = "1", Value = "1"},
            new SelectListItem {Text = "2", Value = "2"},
            new SelectListItem {Text = "3", Value = "3"},
            new SelectListItem {Text = "4", Value = "4"},
        }, "Value", "Text");
}
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Locations</h1>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="box box-primary">
                @using (Html.BeginForm("Create", "Location", FormMethod.Post, new { @class = "", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    if (@ViewBag.Message != null)
                    {
                        <div style="border: 1px solid red; color: orangered">
                            @ViewBag.Message
                        </div>
                    }
                    <div class="box-body">
                        <div class="form-group">
                            <label>Tên địa điểm</label>
                            @Html.TextBoxFor(m => m.Name, new { placeholder = "", @class = "form-control", autocomplete = "off" })
                            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Vĩ độ</label>
                            @Html.TextBoxFor(m => m.Latitude, new { placeholder = "", @class = "form-control", autocomplete = "off", type = "Integer" })
                            @Html.ValidationMessageFor(m => m.Latitude, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Kinh độ</label>
                            @Html.TextBoxFor(m => m.Longitude, new { placeholder = "", @class = "form-control", autocomplete = "off", type = "Integer" })
                            @Html.ValidationMessageFor(m => m.Longitude, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Thứ tự</label>
                            @Html.DropDownListFor(m => m.Position, positionList, "Chọn thứ tự", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Position, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label>Mô tả</label>
                            @Html.TextBoxFor(m => m.Description, new { placeholder = "", @class = "form-control", autocomplete = "off", type = "Integer" })
                            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Lưu</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
}